# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
import os
from typing import Optional

VERSION_FILE_TEMPLATE = """\
# This file is auto-generated by the build system.
# Do not edit this file directly.
__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple
    from typing import Union

    VERSION_TUPLE = Tuple[Union[int, str], ...]
    COMMIT_ID = Union[str, None]
else:
    VERSION_TUPLE = object
    COMMIT_ID = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE
commit_id: COMMIT_ID
__commit_id__: COMMIT_ID

__version__ = version = '{version_str}'
__version_tuple__ = version_tuple = {version_tuple_repr}

__commit_id__ = commit_id = '{commit_id}'
"""


def generate_version_file(filepath: str,
                          version: str,
                          commit_id: Optional[str] = None) -> None:
    if commit_id is None:
        try:
            with open("commit.txt") as f:
                commit_id = f.read()
        except OSError as e:
            raise ValueError(
                f"Error: Could not read file commit.txt. {e})") from e

    version_tuple = version.split(".")

    content = VERSION_FILE_TEMPLATE.format(
        version_str=version,
        version_tuple_repr=repr(version_tuple),
        commit_id=commit_id,
    )

    try:
        if os.path.exists(filepath):
            with open(filepath) as f:
                if f.read() == content:
                    print(f"Version file '{filepath}' is already up-to-date.")
                    return

        # Write the generated content to the specified file.
        with open(filepath, 'w') as f:
            f.write(content)
        abs_path = os.path.abspath(filepath)
        print(f"Successfully generated version file at: {abs_path}")
    except OSError as e:
        raise ValueError(
            f"Error: Could not write to file {filepath}. {e}") from e
